### ISSUE TITLE
Problemas na instalação usando Docker

### ISSUE THREAD

**Issue by hsteinshiromoto** [cuducos/fio-de-ariadne#29]
Caros, quando rodo o programa com Docker eu recebo erros em dois comandos `docker-compose run --rm web python manage.py migrate` e `docker-compose run --rm web python manage.py createsuperuser`

Sou eu que estou rodando algo errado ou é um problema com o código?

Seguem outputs abaixo:

```
$ docker-compose run --rm web python manage.py migrate
Starting fio-de-ariadne_db_1 ... done
Creating fio-de-ariadne_web_run ... done
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  the database system is starting up


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 86, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
    if self.has_table():
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/backends/base/base.py", line 260, in cursor
    return self._cursor()
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/backends/base/base.py", line 236, in _cursor
    self.ensure_connection()
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  the database system is starting up
```

```
$ docker-compose run --rm web python manage.py createsuperuser
reating fio-de-ariadne_web_run ... done

You have 24 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, core, sessions.
Run 'python manage.py migrate' to apply them.

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 100, in handle
    default_username = get_default_username()
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/contrib/auth/management/__init__.py", line 140, in get_default_username
    auth_app.User._default_manager.get(username=default_username)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.cache/pypoetry/virtualenvs/fio-de-ariadne-91Mc58yS-py3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
                                                             ^
```

**Comment by cuducos** [comment]
O problema está descrito na mensagem de erro do primeiro comando que colasse:

> ```
> psycopg2.OperationalError: FATAL:  the database system is starting up
> ```

Você tenta rodar as migrações quando o PostgreSQL ainda está iniciando. 

Tente iniciar o PostgreSQL primeiro com `docker-compose up -d db`, se certifique, lendo as mensagens do log (`docker-compose logs db`), de que o banco de dados está pronto para receber conexões e só então rode as migrações.

**Comment by hsteinshiromoto** [comment]
Obrigado @cuducos, deu tudo certo. A sequência que rodei foi
```
$ docker-compose up -d db
$ docker-compose run --rm web python manage.py migrate
$ docker-compose run --rm web python manage.py crawl
$ docker-compose run --rm web python manage.py createsuperuser
$ docker-compose up
```
